### ISSUE TITLE
more info about this project please ?

### ISSUE THREAD

**Issue by Adamkaram** [ryuryu10/KeyCastr-windows#1]
i like keycastr for mac and i searched out for version that i can used in windows

**Comment by ryuryu10** [comment]
I was working on keycastr for Mac because I wanted to use it on Windows.
But when I bought a MacBook, the development of the project was stopped.
We will proceed with the development of this project again as soon.
Thank you very much for your interest.

**Comment by Adamkaram** [comment]
i'm admire of keycastr and wish you bring this project to life again
